filter {
  if [agent][type] == "filebeat" and [log][file][path] == "/var/log/auth.log" {
    if "Failed password" in [message] {
      grok {
        match => {
          "message" => "Failed password for (invalid user )?%{USERNAME:[user][name]} from %{IP:[source][ip]} port %{NUMBER:[source][port]:int} ssh2(: %{GREEDYDATA:[system][auth][ssh][signature]})?"
        }
      }

      mutate {
        replace => {
          "[event][action]" => "logon-failed"
          "[event][kind]" => "event"
          "[event][category]" => "authentication"
          "[event][type]" => "info"
          "[event][outcome]" => "failure"
        }
      }
    }
  }
}
